### ISSUE TITLE
Potential Nullpointer if validators is set to null

### ISSUE THREAD

**Issue by amjmhs** [T-Systems-MMS/openapi-typescript-angular-generator#15]
https://github.com/T-Systems-MMS/openapi-typescript-angular-generator/blob/97da834b5db59e1f04d86999ff642dc44e7a834d/src/formcontrol.ts#L36

Check for further occurrences!

**Comment by cogidoo** [comment]
I tried to replicate this issue with a test-case but come to the conclusion that the api must be used the wrong way. Because of the types, the nullpointer is not possible. Please check the use of this generator within your project.

**Comment by cogidoo** [comment]
@malaupa should we close this?

**Comment by malaupa** [comment]
Yes, @cogidoo we should close this.
