### ISSUE TITLE
Error with creating a new TypedFormGroup

### ISSUE THREAD

**Issue by wagmannj** [T-Systems-MMS/openapi-typescript-angular-generator#29]
Hi, i have a problem with using TypedFormGroup. I got the error message:
"LoginDialog_Host.ngfactory.js? [sm]:1 ERROR TypeError: Class constructor FormGroup cannot be invoked without 'new'" in my code
```typescript
 constructor(
    public dialogRef: MatDialogRef<LoginDialog>,
    public authService: AuthenticationService,
    @Inject(MAT_DIALOG_DATA) public data: DialogData) {
      const factory = new LoginDto.FormControlFactory(this.model);
      this.form = new TypedFormGroup<LoginDto>({
        password: null, // factory.createFormControl<string>('password'),
        user: null, // factory.createFormControl<string>('user')
      });
  }
```
Angular CLI: 8.1.1
Node: 12.6.0
OS: linux x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.1
@angular-devkit/build-angular     0.801.1
@angular-devkit/build-optimizer   0.801.1
@angular-devkit/build-webpack     0.801.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@angular/cdk                      8.0.2
@angular/material                 8.0.2
@ngtools/webpack                  8.1.1
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2

package.json:
"dependencies": {
    "@angular/animations": "~8.1.1",
    "@angular/cdk": "~8.0.2",
    "@angular/common": "~8.1.1",
    "@angular/compiler": "~8.1.1",
    "@angular/core": "~8.1.1",
    "@angular/forms": "~8.1.1",
    "@angular/material": "^8.0.2",
    "@angular/platform-browser": "~8.1.1",
    "@angular/platform-browser-dynamic": "~8.1.1",
    "@angular/router": "~8.1.1",
    "hammerjs": "^2.0.8",
    "openapi-typescript-angular-generator": "^5.0.0",
    "rxjs": "~6.5.2",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },

tsconfig.json:

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}

**Comment by amjmhs** [comment]
Can you please provide the generated code of `LoginDto`.

**Comment by wagmannj** [comment]
Thx, geht generated code is:

/*
 * Copyright(c) 1995 - 2018 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 *
 * partnership for decision makers
 * Provides the services to administrate the application
 *
 * OpenAPI spec version: 0.1
 * Contact: wagmannj@arcor.de
 *
 * NOTE: This class is auto generated by the openapi-typescript-angular-generator.
 * https://github.com/T-Systems-MMS/openapi-typescript-angular-generator
 * Do not edit the class manually.
 */

import { ValidatorFn, Validators } from '@angular/forms';
import { BaseFormControlFactory } from 'openapi-typescript-angular-generator';



export interface LoginDto { 
    user: string;
    password: string;
}

/**
 * Namespace for property- and property-value-enumerations of LoginDto.
 */
export namespace LoginDto {
    /**
     * All properties of LoginDto.
     */
    export enum Properties {
        user = 'user',
        password = 'password'
    }

    /**
    * A map of tuples with error name and `ValidatorFn` for each property of LoginDto.
    */
    export const ModelValidators: {[K in keyof LoginDto]: [string, ValidatorFn][]} = {
        user: [
                ['required', Validators.required],
        ],
        password: [
                ['required', Validators.required],
        ],
    };

    /**
    * The FormControlFactory for LoginDto.
    */
    export class FormControlFactory extends BaseFormControlFactory<LoginDto> {

        /**
         * Constructor.
         *
         * @param model An existing model for LoginDto.
         *              If given, all form-controls of the factory automatically have the value of this model. If this
         *              model is not given, all values are `null`.
         */
        constructor(
          model: LoginDto = {
            user: null,
            password: null,
          }
        ) {
            super(model, LoginDto.ModelValidators);
        }
    }

}

**Comment by malaupa** [comment]
Can you provide a stackblitz project to reproduce the error case.

By the way: You have to create the FormControlFactory using the new operator so the created object can be used to create form controls.

**Comment by malaupa** [comment]
Closed due to inactivity.
